#!/bin/bash
# author zhanzhihu

#*/5 * * * * /usr/local/bin/check_taos.sh >> /root/logs/check_taos.log 2>&1
is_active=$(docker ps |grep tdengine |wc -l )

if [ $is_active -eq 0 ]; then
  echo "$(date +"%Y-%m-%d %H:%M:%S") start taos"
  systemctl start docker
  systemctl stop taosd
  systemctl stop taosadapter  
  docker start tdengine
  else
    echo "$(date +"%Y-%m-%d %H:%M:%S") taos is running"
fi
