version: "3"
services:
  taosnode2:
      restart: always
      image: tdengine/tdengine:3.0.1.6
      hostname: taosnode2
      container_name: taosnode2
      privileged: true
      ports:
        - 7020:7020
        - 7030-7042:7030-7042/tcp
        - 7030-7042:7030-7042/udp
      volumes:
        - ./etc/node2etc/taos.cfg:/etc/taos/taos.cfg:ro
        - ./data/node2data:/var/lib/taos/:rw
        - ./log/node2log:/var/log/taos/:rw
      extra_hosts:
        - "taosnode1:192.168.1.118"
      networks:
        noodb:
          ipv4_address: 172.23.0.4    
  taosnode3:
      restart: always
      image: tdengine/tdengine:3.0.1.6
      hostname: taosnode3
      container_name: taosnode3
      privileged: true
      ports:
        - 8020:8020
        - 8030-8042:8030-8042/tcp
        - 8030-8042:8030-8042/udp
      volumes:
        - ./etc/node3etc/taos.cfg:/etc/taos/taos.cfg:ro
        - ./data/node3data:/var/lib/taos/:rw
        - ./log/node3log:/var/log/taos/:rw
      extra_hosts:
        - "taosnode1:192.168.1.118"
      networks:
        noodb:
          ipv4_address: 172.23.0.5
networks:
  noodb:
    name: taos_network
    ipam: 
      config: 
        - subnet: 172.23.0.0/16
