version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  redis:
    image: redis
    restart: always
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

  kafka:
    image: confluentinc/cp-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: 172.20.0.6:2181
    depends_on:
      - zookeeper
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.6

  thingsboard:
    image: thingsboard/tb-postgres
    restart: always
    ports:
      - "8080:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.0.3:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_QUEUE_TYPE: kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 172.20.0.5:9092
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
    depends_on:
      - postgres
      - kafka
    networks:
      mynetwork:
        ipv4_address: 172.20.0.7

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      mynetwork:
        ipv4_address: 172.20.0.8

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - thingsboard
    networks:
      mynetwork:
        ipv4_address: 172.20.0.9

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
